site_name: Akane's blog
site_url: https://akane.github.io/blog/
repo_url: https://github.com/Akane-6730/blog


nav:
  - Home: index.md  
  - Notes: 
      - C:  C/C.md


theme: 
  name: material
  language: "zh"
  logo: assets/MIKASA.png
  favicon: assets/MIKASA.png
  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.sections
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
