site_name: Akane's blog
site_url: https://akane.github.io/blog/
repo_url: https://github.com/Akane-6730/blog


nav:
  - Home: 
      - Home: index.md  
      - About: about.md
  - CS:
      - PracticalSkills:
          - CS/PracticalSkills/0_linux-shell.md
          
      - 编程语言:
          - C:
              - CS/编程语言/C/C.md
              - CS/编程语言/C/一些概念性知识.md
              - CS/编程语言/C/一些常犯的小错误.md
              - CS/编程语言/C/输入.md
  - Math:
      - Calculus:
          - Math/calculus/解题方法思路整理.md
          - Math\calculus\定理证明思路.md
      - Linear Algebra:
          - Math/Linear Algebra/Linear Algebra.md

  - Language:
      - English:
          - 大英Ⅲ:
              - VLSⅡ: Language/English/大英Ⅲ/VLSⅡ.md
              - ICⅡ: Language/English/大英Ⅲ/ICⅡ.md
  - CTF:
      - CTF\Crypto\My CTF competition history.md
      - Crypto:
          - CTF\Crypto\Introduction to CryptoHack.md

theme: 
  name: material
  language: "zh"
  logo: assets/MIKASA.png
  favicon: assets/MIKASA.png
  icon:
    previous: fontawesome/solid/angle-left  # 上一页图标
    next: fontawesome/solid/angle-right  # 下一页图标
    repo: fontawesome/brands/github  # GitHub仓库图标
    view: material/eye  # 查看图标
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - header.autohide
  font: false
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - md_in_html
  - attr_list

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details


extra_css:  # 额外CSS文件设置
    - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css  # KaTeX样式文件
    - css/custom.css  # 自定义CSS文件
    - css/neoteroi-mkdocs.css  # 另一个自定义CSS文件
    - css/custom-carousel.css
    - css/counter.css
    - https://cdn.tonycrane.cc/utils/katex.min.css  # 另一个KaTeX样式文件
    - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css  # JetBrains Mono字体样式
    - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css  # LXGW字体样式


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML
  - javascripts/mathjax.js  #Latex支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6   #Latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js   #Latex支持
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

# plugins:
#     - git-revision-date-localized:
#         enable_creation_date: true
#         type: date
#         fallback_to_build_date: true
#         timezone: Asia/Shanghai
#         locale: zh
#         exclude:
#             - index.md